export type Item = typeof items[0];
export const items = [
  { id: 1, visible: true, order: 1, content: "Introducción general", categoryId: 1 },
  { id: 2, visible: false, order: 2, content: "Documento privado", categoryId: 2 },
  { id: 3, visible: true, order: 3, content: "Guía pública", categoryId: 3 },
  { id: 4, visible: true, order: 4, content: "Política general", categoryId: 1 },
  { id: 5, visible: false, order: 5, content: "Acceso de administrador", categoryId: 4 },
  { id: 6, visible: true, order: 6, content: "Preguntas frecuentes", categoryId: 5 },
  { id: 7, visible: true, order: 7, content: "Manual del usuario", categoryId: 3 },
  { id: 8, visible: false, order: 8, content: "Reporte confidencial", categoryId: 2 },
  { id: 9, visible: true, order: 9, content: "Actualización del sistema", categoryId: 4 },
  { id: 10, visible: true, order: 10, content: "Notas de la versión", categoryId: 1 },
  { id: 11, visible: false, order: 11, content: "Estadísticas internas", categoryId: 4 },
  { id: 12, visible: true, order: 12, content: "Tutorial básico", categoryId: 3 },
  { id: 13, visible: true, order: 13, content: "Soporte técnico", categoryId: 5 },
  { id: 14, visible: false, order: 14, content: "Estrategia empresarial", categoryId: 2 },
  { id: 15, visible: true, order: 15, content: "Bienvenida al sistema", categoryId: 1 },
  { id: 16, visible: true, order: 16, content: "Instrucciones de uso", categoryId: 3 },
  { id: 17, visible: false, order: 17, content: "Datos reservados", categoryId: 2 },
  { id: 18, visible: true, order: 18, content: "Indicaciones para el soporte", categoryId: 5 },
  { id: 19, visible: true, order: 19, content: "Panel de administrador", categoryId: 4 },
  { id: 20, visible: true, order: 20, content: "Guía rápida", categoryId: 1 },
  { id: 21, visible: false, order: 21, content: "Configuraciones avanzadas", categoryId: 4 },
  { id: 22, visible: true, order: 22, content: "Presentación institucional", categoryId: 1 },
  { id: 23, visible: true, order: 23, content: "FAQ extendido", categoryId: 5 },
  { id: 24, visible: false, order: 24, content: "Informe privado", categoryId: 2 },
  { id: 25, visible: true, order: 25, content: "Recursos disponibles", categoryId: 3 },
  { id: 26, visible: true, order: 26, content: "Política de soporte", categoryId: 5 },
  { id: 27, visible: true, order: 27, content: "Información de contacto", categoryId: 3 },
  { id: 28, visible: false, order: 28, content: "Auditoría interna", categoryId: 4 },
  { id: 29, visible: true, order: 29, content: "Inicio rápido", categoryId: 1 },
  { id: 30, visible: false, order: 30, content: "Datos sensibles", categoryId: 2 }
];